// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfzuazvdredjmalgylay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmenVhenZkcmVkam1hbGd5bGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjMwNzUsImV4cCI6MjA1NjEzOTA3NX0.Rj57goprtI4XSx3laypqrJADC347FnYWWDVAhGNeoRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);