// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouvhccjagzexokccslqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dmhjY2phZ3pleG9rY2NzbHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTMwMTIsImV4cCI6MjA1NjY2OTAxMn0.POmCMtWSFeCGEOFBCHrQc6fUYhZgDkvExdRjBz8CFyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);